# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'
  strategy:

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: 9.x
- script: npm install

- task: Bash@3
  inputs:
      targetType: 'inline'
      script: echo $DEBUG_KEY | base64 --decode > android/app/debug.keystore && (cd android && ./gradlew assembleDebug) && ls $(Build.ArtifactStagingDirectory) && ls android/app/build/outputs/apk/debug/

- task: GithubRelease@0 
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: uploads api
    repositoryName: xavs/react-native
    tagSource: manual
    tag: $(Build.BuildNumber)      
    assets: |
         $(Build.ArtifactStagingDirectory)/android/app/build/outputs/apk/debug/app-debug.apk
