name: Android CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - name: Setup android keys
        env: # Or as an environment variable
          DEBUG_KEY: ${{ secrets.DEBUG_KEY }}
        run: "echo $DEBUG_KEY > test && head test && echo -e $DEBUG_KEY | base64 --decode > android/app/debug.keystore && echo $(pwd) && cat android/app/debug.keystore"
        shell: bash

      - name: Generate apk
        run: "(cd android && ./gradlew assembleDebug) && echo $(Build.ArtifactStagingDirectory) && ls android/app/build/outputs/apk/debug/"
        shell: bash
        
