name: Android CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: setup nodejs
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'    
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install nodejs dependencies
    - run: npm install

    - name: Setup android keys
      shell: bash
      run: echo $DEBUG_KEY | base64 --decode > android/app/debug.keystore 

    - name: Generate apk
      shell: bash
      run: | 
        base64 --decode > android/app/debug.keystore 
        && (cd android && ./gradlew assembleDebug) 
        && echo $(Build.ArtifactStagingDirectory) 
        && ls android/app/build/outputs/apk/debug/

