name: Android CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'    
