name: Android CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'    
      - name: setup co
        uses: actions/checkout@v2
  
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
 
      - name: Install nodejs dependencies
        run: npm install
        
      - name: Setup android keys
        env: # Or as an environment variable
          DEBUG_KEY: ${{ secrets.DEBUG_KEY }}
        run: "mkdir -p android/app/ && echo -e $DEBUG_KEY | base64 --decode > android/app/debug.keystore && echo $(pwd) && cat android/app/debug.keystore && ls -la /home/runner/work/react-native/react-native/android/app/"
        shell: bash

      - name: Generate apk
        run: "(cd android && ./gradlew assembleDebug) && ls android/app/build/outputs/apk/debug/"
        shell: bash
      - name: upload apk
        uses: actions/upload-artifact@v1
        with:
          name: simpley-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
        
